export const MOCK_BANKS = [
  {
    id: "bank_1",
    userId: "user_1",
    itemId: "item_1",
    institutionId: "ins_1",
    institutionName: "Chase Bank",
    status: "ACTIVE" as const,
    dwollaFundingUrl: "https://api-sandbox.dwolla.com/funding-sources/1",
    isDwollaLinked: true,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bank_2",
    userId: "user_1",
    itemId: "item_2",
    institutionId: "ins_2",
    institutionName: "Bank of America",
    status: "ACTIVE" as const,
    dwollaFundingUrl: "https://api-sandbox.dwolla.com/funding-sources/2",
    isDwollaLinked: true,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bank_3",
    userId: "user_1",
    itemId: "item_3",
    institutionId: "ins_3",
    institutionName: "Wells Fargo",
    status: "LOGIN_REQUIRED" as const, // Should be filtered out
    dwollaFundingUrl: null,
    isDwollaLinked: false,
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
